name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:latest ./
      - name: Login to registry
        run: docker login --username=${{ secrets.DOCKER_USERNAE }} --password ${{ secrets.DOCKER_PASSWORD }} ccr.ccs.tencentyun.com/
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >> ~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.HOST_USERNAME }}
          SSH_KEY: ${{ secrets.HOST_SSH_KEY }}
          SSH_HOST: ${{ secrets.HOST }}
      - name: Restart my desk server
        run: ssh staging 'cd /root/docker/my_desk && docker-compose stop my-desk-app && docker pull ${{secrets.DOCKER_REPOSITORY}}:latest && docker-compose up -d  my-desk-app'
